### ISSUE TITLE
override default behavior of Modal

### ISSUE THREAD

**Issue by begoat** [rsuite/interactions#11]
Shall we support
1. customize `Modal.title`
2. override common Modal props (size, full, overflow, etc.)

**Comment by SevenOutman** [comment]
我们目前提供的 API 都是为了让 modal 的样式、表现等更加一致。你提议的这些让 modal 更加多样化的选项，我想也许可以通过专门提供一个完全自定义的例如 `modal` 方法来支持。

或者，如果你提议的这些属性不是为了 per-modal 去设置，而是为了设置 modal 的统一样式，我们也可以专门提供一个 API 来进行全局设置。

**Comment by begoat** [comment]
嗯

第二点你提到的保持全局的一致，我也确实有必要，不过如果我们可以通过默认值，那本身也是一种尽量保持统一的方案
第一点的话 感觉这个参数确实需要，因为有需求是需要title的～

你觉的呢

**Comment by begoat** [comment]
你提到的全局统一，我实际用的时候发现确实很有必要

比如 ok、cancel按钮的文字，每个地方都要写一遍，用的地方不多的话，这种感觉问题不大

**Comment by SevenOutman** [comment]
具体是什么场景会如何用到 title？

**Comment by begoat** [comment]
title 用于 展示操作的简写
下面是 description

比如
上面是`停用项目`，下面是`你确定要停用这个项目吗`
