### ISSUE TITLE
Buttons are hard-coded to Chinese

### ISSUE THREAD

**Issue by hallids** [rsuite/interactions#5]
Am I missing something?

**Comment by SevenOutman** [comment]
@hallids Thanks for your feedback. 

The initial goal of this library was to provide simplest API for calling modals (same with native ones), and customization was not taken into consideration. There will probably be an additional argument for customizing modals for each method in future releases.

**Comment by SevenOutman** [comment]
@hallids It's included in [`v1.1.1`](https://github.com/rsuite/interactions/releases/tag/v1.1.1)
